import { Colors } from '@/constants/theme';
import { useRouter } from 'expo-router';
import { ChevronLeft } from 'lucide-react-native';
import { Platform, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import Animated, { FadeIn } from 'react-native-reanimated';
import { SafeAreaView } from 'react-native-safe-area-context';

export default function TermsScreen() {
  const router = useRouter();

  const handleBack = () => {
    if (router.canGoBack()) {
      router.back();
    } else {
      router.replace('/login');
    }
  };

  return (
    <SafeAreaView style={styles.container}>
      <View style={styles.header}>
        <Pressable onPress={handleBack} style={styles.backButton}>
          <ChevronLeft color="#FFF" size={28} />
        </Pressable>
        <Text style={styles.headerTitle}>LEGAL</Text>
        <View style={{ width: 44 }} />
      </View>

      <ScrollView
        style={styles.content}
        contentContainerStyle={styles.scrollContent}
        showsVerticalScrollIndicator={false}
      >
        <Animated.View entering={FadeIn.delay(200).duration(800)}>
          <Text style={styles.title}>Terms of Service</Text>
          <Text style={styles.lastUpdated}>Last Updated: April 22, 2026</Text>

          <Text style={styles.intro}>
            Welcome to Memecam. By accessing or using our application, you agree to be bound by these Terms of Service.
          </Text>

          <View style={styles.section}>
            <Text style={styles.sectionTitle}>1. Services Provided</Text>
            <Text style={styles.sectionText}>
              Memecam provides AI-powered meme generation tools. You understand that the "fire" (meme captions) is generated by Artificial Intelligence and may vary in accuracy or tone.
            </Text>
          </View>

          <View style={styles.section}>
            <Text style={styles.sectionTitle}>2. Subscriptions & Billing</Text>
            <Text style={styles.sectionText}>
              • Premium subscriptions are processed via Google Play Billing.
              {"\n"}• Subscriptions automatically renew unless cancelled at least 24 hours before the end of the current period.
              {"\n"}• You can manage or cancel your subscription anytime via your Google Play Store account settings.
            </Text>
          </View>

          <View style={styles.section}>
            <Text style={styles.sectionTitle}>3. AI Usage & Content</Text>
            <Text style={styles.sectionText}>
              You retain ownership of the original images you upload. By using the app, you grant Memecam a non-exclusive license to process these images through our AI service (Google Gemini) solely to provide the meme generation service.
            </Text>
          </View>

          <View style={styles.section}>
            <Text style={styles.sectionTitle}>4. User Conduct</Text>
            <Text style={styles.sectionText}>
              You agree not to use Memecam to generate content that is illegal, hateful, or violates the rights of others. We reserve the right to terminate accounts that violate these guidelines.
            </Text>
          </View>

          <View style={styles.section}>
            <Text style={styles.sectionTitle}>5. Account Deletion</Text>
            <Text style={styles.sectionText}>
              You may extinguish your "fire" (delete your account) at any time through the Settings menu in the app. This will permanently delete your profile and all generated memes from our servers.
            </Text>
          </View>

          <View style={styles.divider} />

          <Text style={styles.title}>Privacy Policy</Text>
          <Text style={styles.lastUpdated}>Last Updated: April 22, 2026</Text>

          <Text style={styles.intro}>
            Your privacy is paramount. This policy explains how we protect your data in the fire lab.
          </Text>

          <View style={styles.section}>
            <Text style={styles.sectionTitle}>1. Information We Collect</Text>
            <Text style={styles.bulletItem}>• Account Info: Name and email via Google Sign-In.</Text>
            <Text style={styles.bulletItem}>• Media: Images you capture or upload for meme generation.</Text>
            <Text style={styles.bulletItem}>• Usage Data: Statistics on meme generation to improve our AI models.</Text>
          </View>

          <View style={styles.section}>
            <Text style={styles.sectionTitle}>2. How We Use Data</Text>
            <Text style={styles.sectionText}>
              We use Supabase for secure cloud storage and Google Gemini for AI analysis. Images are processed to generate captions and stored only if you choose to save them to your profile.
            </Text>
          </View>

          <View style={styles.section}>
            <Text style={styles.sectionTitle}>3. Data Retention</Text>
            <Text style={styles.sectionText}>
              We retain your data only as long as your account is active. Once an account is deleted, all associated data is purged from our Supabase database and storage buckets.
            </Text>
          </View>

          <View style={styles.section}>
            <Text style={styles.sectionTitle}>4. Third-Party Partners</Text>
            <Text style={styles.sectionText}>
              We share data only with necessary service providers:
              {"\n"}• Google (Authentication & AI)
              {"\n"}• Supabase (Database & Storage)
            </Text>
          </View>

          <View style={styles.section}>
            <Text style={styles.sectionTitle}>5. Contact Us</Text>
            <Text style={styles.sectionText}>
              For legal inquiries or data requests, contact us at:
              {"\n"}cubiant@gmail.com
            </Text>
          </View>

          <Text style={[styles.sectionText, { marginTop: 20, marginBottom: 40, textAlign: 'center', opacity: 0.5 }]}>
            © 2026 Memecam. All rights reserved.
          </Text>
        </Animated.View>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0A0A0A',
    ...Platform.select({
      web: {
        height: '100dvh',
      },
    }),
  },
  header: {
    height: 60,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.05)',
  },
  headerTitle: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: '900',
    letterSpacing: 2,
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255,255,255,0.05)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  content: {
    flex: 1,
  },
  scrollContent: {
    padding: 24,
  },
  title: {
    fontSize: 28,
    fontWeight: '900',
    color: '#FFF',
    marginBottom: 8,
    letterSpacing: -0.5,
  },
  lastUpdated: {
    fontSize: 14,
    color: Colors.dark.accent,
    fontWeight: '700',
    marginBottom: 24,
  },
  intro: {
    fontSize: 16,
    color: '#FFF',
    lineHeight: 24,
    marginBottom: 32,
    fontWeight: '500',
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: Colors.dark.accent,
    marginBottom: 10,
  },
  sectionText: {
    fontSize: 15,
    color: Colors.dark.muted,
    lineHeight: 22,
    fontWeight: '500',
  },
  bulletItem: {
    fontSize: 15,
    color: Colors.dark.muted,
    lineHeight: 22,
    fontWeight: '500',
    marginLeft: 12,
    marginTop: 4,
  },
  divider: {
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.1)',
    marginVertical: 48,
  },
});
